CREATE TABLE IF NOT EXISTS SOURCES (
url TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS DOCUMENTS (
url TEXT PRIMARY KEY,
source TEXT NOT NULL,
title TEXT NOT NULL,
rate INTEGER NOT NULL,
fav INTEGER NOT NULL,
date DATE,
modified DATE,
format TEXT,
FOREIGN KEY(source) REFERENCES SOURCES(url)
);

CREATE TABLE IF NOT EXISTS BOOKMARKS (
bookmark INTEGER PRIMARY KEY
);
